### ISSUE TITLE
Bad icons size after last update (0.9.7.1)

### ISSUE THREAD

**Issue by FivviT** [zayronxio/Macos-sierra-CT#11]
Hi.
I found the next problem after install 0.9.7.1 version.
My working machine is a laptop with Ubuntu 18.10 with Gnome DE.
After I use any multimedia hotkey appears icon with bad size.

For example
![screenshot from 2019-02-25 10-20-23](https://user-images.githubusercontent.com/7015571/53323610-49e73200-38e7-11e9-9922-1d4565ee31e9.png)

**Comment by FivviT** [comment]
UPD. Only for volume hotkeys.

**Comment by zayronxio** [comment]
I'll solve it, if you do not want to wait, open the theme folder, look for the index.theme file, edit it with any simple text editor, look for the lines:

[panel/24]
Size=24
Context=Status
Type=Scalable

add the following:

MinSize=8
MaxSize=256

**Comment by FivviT** [comment]
It works. Thanks.

**Comment by zayronxio** [comment]
let me know if it works, thanks

**Comment by FivviT** [comment]
Yes, it works )
But I found another thing that will be good to fix/change. Multimedia icons that appear on change volume level, have a different position in the rectangle.
Here 70px
![image](https://user-images.githubusercontent.com/7015571/53342706-479ccc00-3917-11e9-8a46-0ca1540619b6.png)
And here 63px
![image](https://user-images.githubusercontent.com/7015571/53342779-71ee8980-3917-11e9-9631-f4f533e52b0e.png)

**Comment by zayronxio** [comment]
solved in the latest version available in opendesktop
