### ISSUE TITLE
Reporting Bugs

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [zayronxio/Macos-sierra-CT#12]
Greetings, zyronXIO.
Thank for the effort you make in each update.

I've tried to post a comment for six days from the 0.9.7 version, but I don't know what's wrong with Opendesktop.

So, i've tried the 0.9.7 and 0.9.7.1 viersion, now Mojave, and it's still doesn't work completely on Pantheon Desktop, I tested it and there are several problems. For example, the .tar Classic version is still 0.9.6.4 version and, in this version, the top panel icons don't have the new 0.9.7.1 version; also the open folders in the Classic version aren't displayed, there's only a empty space, and in the Light and Dark  version, the open folder doesn't correspond to the theme, it's a different folder of different color.

On the ohter hand, the size of the icons in the top panel is still too large and the notification icons doesn't appear in Classic version. I also found that the Albert App Laucher aplication doesn't show the theme icons, and in Plank Dock, the Rubbish Bin icon is the same of the file manager, just change when you touch it with the cursor.
These problems are only in Pantheon Desktop, except for the plank dock, it's in all desktops xD

That's all in my report xD
Thanks for your great work :D
I leave some screenshots:https://imgur.com/a/Eo9JYd6

**Comment by zayronxio** [comment]
I have tried elementary juno, and if I ran into some problems, however not as many as those mentioned, please check again installing version 0.9.7.2 to be released soon

**Comment by zayronxio** [comment]
try the latest version available in opendesktop, 0.9.7.2
