### ISSUE TITLE
Pixel perfect 22px symbolic icons

### ISSUE THREAD

**Issue by Luwx** [zayronxio/Macos-sierra-CT#13]
A while back I created some, they can be found here: https://github.com/Luwx/Dotfiles/tree/master/.local/share/icons/MacOSX_ONE8_dark/48x48/symbolic

Can you add them?

**Comment by zayronxio** [comment]
@Luwx the icons are present from previous versions [imagen](https://i.imgur.com/Cth1H1Q.png)
