### ISSUE TITLE
Blurry logos

### ISSUE THREAD

**Issue by MellowPhi** [zayronxio/Macos-sierra-CT#15]
Hey zyronXIO,
 I just noticed the icons released on **2019-03-06** on https://www.gnome-look.org/p/1210856/
contains blurry icons on the light,classic and dark-mode packs. Here is a list of the icons

1) Airplane mode/ WiFi toggle 
2) Keyboard backlit
3) Brightness 
4) Touchpad on/off toggle 

![backlight_](https://user-images.githubusercontent.com/48370987/54064410-0f6a8700-424f-11e9-8f16-e6331a8f6065.png)
keyboard backlit
![brightness_](https://user-images.githubusercontent.com/48370987/54064414-11cce100-424f-11e9-9454-1b37f9e1c97d.png)
brightness 
![volume_](https://user-images.githubusercontent.com/48370987/54064416-15606800-424f-11e9-967e-b1c632c7a215.png)
Whist volume is working fine. This for ref purpose.

I tested with earlier version released on **2019-03-04** and the same problem exist. However 
the `v0.9.7` from ur git release, there seem be to no issues with any of the icons I listed above.
`v0.9.7` works perfectly. 

Hope you look into it, and thanks for your amazing work.
Cheers

**Comment by zayronxio** [comment]
download the master version from here, github, and tell me if something changed, thanks for reportart

**Comment by MellowPhi** [comment]
everything works except touchpad 
![touchpad](https://user-images.githubusercontent.com/48370987/54067448-17d8b700-427b-11e9-9cbe-b3aa7718df9d.png)
touchpad enabled
![touchpad_](https://user-images.githubusercontent.com/48370987/54067449-1ad3a780-427b-11e9-9f78-5b2d8af53ab5.png)
touchpad disabled

cheers for the quick fix :)

**Comment by cajuuh** [comment]
my volumes don't work well the the other ones are fine apparently

[![blurred-Issue.png](https://i.postimg.cc/ZR8Fmghk/blurred-Issue.png)](https://postimg.cc/N90r7dMb)

**Comment by FivviT** [comment]
> my volumes don't work well the the other ones are fine apparently
> 
> [![blurred-Issue.png](https://camo.githubusercontent.com/84b0ddfc9505fa28f0592bf9d81d278ff89f75f6/68747470733a2f2f692e706f7374696d672e63632f5a5238466d67686b2f626c75727265642d49737375652e706e67)](https://postimg.cc/N90r7dMb)

Hi @zayronxio. 
Can you fix this?
Also will be really great if you will add icon for volume over 100%
![Screenshot from 2019-04-17 10-30-10](https://user-images.githubusercontent.com/7015571/56269281-02696f00-60fc-11e9-81c5-59df12708649.png)
 
Thanks)

**Comment by zayronxio** [comment]
check now

**Comment by FivviT** [comment]
HI @zayronxio.
Yes it works. Thanks
