### ISSUE TITLE
Icon for volume over 100% 

### ISSUE THREAD

**Issue by FivviT** [zayronxio/Macos-sierra-CT#21]
Hi.
Here is in Ubuntu 18.10 and higher icon for volume over 100%.
![image](https://user-images.githubusercontent.com/7015571/56519909-cbf08180-654b-11e9-98f5-e6392dcbb6ab.png)

Can you add this icon?
Thank you in advance.

**Comment by zayronxio** [comment]
I did not know about the existence of this icon, if I add it,

**Comment by FivviT** [comment]
Do you need steps to reproduce or smth else? How can I help?

**Comment by zayronxio** [comment]
what is the name of the icon

**Comment by FivviT** [comment]
I found that in `Yaru` icons set that this icon called `audio-volume-overamplified-symbolic.svg`. 

![image](https://user-images.githubusercontent.com/7015571/56714670-349f5000-673e-11e9-8f7e-9199a36127eb.png)

**Comment by zayronxio** [comment]
icon added

**Comment by FivviT** [comment]
@zayronxio Thanks.
But it looks blurry like here
https://github.com/zayronxio/Mojave-CT/issues/15
