### ISSUE TITLE
Elementary os is missing icon, panel icon is too large

### ISSUE THREAD

**Issue by Yakumo-Yukari** [zayronxio/Macos-sierra-CT#5]
![2018-11-30 20 01 23](https://user-images.githubusercontent.com/12076232/49288135-dc3f8b80-f4da-11e8-85c8-34799cb2933b.png)

No notification icon in elementary os

**Comment by bl4ckb1rd77** [comment]
edit index.theme and add elementary on Inherits

`Inherits=Adwaita,breeze,breeze-dark,hicolor,gnome,elementary`

**Comment by Yakumo-Yukari** [comment]
Thank you
