### ISSUE TITLE
[Request] Create Panel Icons

### ISSUE THREAD

**Issue by btd1337** [zayronxio/Macos-sierra-CT#6]
Please, Could you create the panel icons?

**Comment by zayronxio** [comment]
The set has icons for the panel. What icons are you referring to?

**Comment by btd1337** [comment]
You are using the traditional La Capitaine icons.

I'm referring to the original OSX panel icons.

![ximg_55402a5b363d3 png pagespeed gp jp jw pj ws js rj rp rw ri cp md ic jvssgbl7o0](https://user-images.githubusercontent.com/11943860/52099367-1b14bf00-25ba-11e9-9cc6-4051a142362a.jpg)

**Comment by zayronxio** [comment]
I am currently working on a plasma theme for sierra ct macos, this project at the end will provide the necessary base to incorporate the icons that you mention in the pack, I hope to have it ready soon, regards

**Comment by btd1337** [comment]
@zayronxio I started this creation but I'm not good with svg. Either way is an initial step for your project. 

https://github.com/btd1337/OSX-Indicator-Icons-Design

**Comment by zayronxio** [comment]
thanks, in the next update add icons of the battery, network, user, and messages (pidgin), I appreciate your contribution,

**Comment by btd1337** [comment]
I look forward to the next update!

**Comment by btd1337** [comment]
I appreciate you started this feature. I've noticed that the battery icon needs to grow in size to keep the same dimensions as other indicator icons. Would it be possible?

![captura de tela de 2019-02-18 13-36-51](https://user-images.githubusercontent.com/11943860/52964915-55d07280-3382-11e9-9ae0-5bb37a107410.png)

![captura de tela de 2019-02-18 16-08-24](https://user-images.githubusercontent.com/11943860/52971786-85d64080-3397-11e9-9037-18a07ba186a2.png)

**Comment by zayronxio** [comment]
I hope to solve it today.

**Comment by zayronxio** [comment]
try now.

**Comment by btd1337** [comment]
There was no changes. Apparently the bluetooth indicator has the same problem. They appear to be on a smaller scale than other icons.

![captura de tela de 2019-02-21 12-30-55](https://user-images.githubusercontent.com/11943860/53180832-2a919180-35d5-11e9-8d22-0f36302d48e8.png)


![captura de tela de 2019-02-21 12-31-55](https://user-images.githubusercontent.com/11943860/53180844-31200900-35d5-11e9-87a7-248df3ba56ce.png)

Look [elementary icon pack](https://github.com/elementary/icons) looks like: 

![captura de tela de 2019-02-21 12-30-21](https://user-images.githubusercontent.com/11943860/53180956-6593c500-35d5-11e9-9732-d33030c278aa.png)


DE: Gnome 3.30

**Comment by btd1337** [comment]
Looking at the OSX icon I think the problem should be in the icon height dimensions.

**Comment by zayronxio** [comment]
unfortunately I do not have gnome in my distro, nor a laptop to view the icon, please try the branch trayicons

**Comment by btd1337** [comment]
How battery and bluetooth looks like in your DE?

**Comment by zayronxio** [comment]
use kde, and the icons look more similar to mac, but this depends on the topics of plasma and not those of the i

**Comment by btd1337** [comment]
Now in trayicons branch:

![captura de tela de 2019-02-22 14-25-50](https://user-images.githubusercontent.com/11943860/53259462-de665000-36ad-11e9-8349-ab64d58ebca0.png)

![captura de tela de 2019-02-22 14-26-03](https://user-images.githubusercontent.com/11943860/53259474-e7572180-36ad-11e9-89cb-86b3fc75cdea.png)

Original mac:

![52099367-1b14bf00-25ba-11e9-9cc6-4051a142362a](https://user-images.githubusercontent.com/11943860/53259591-343af800-36ae-11e9-8618-76427d00a58f.jpg)

I think it needs some tweaking:

Increase height, rounded edges and more internal padding (more light spacing).

**Comment by zayronxio** [comment]
I have resized the icon, I had to use a smaller ruler, I hope this does not generate blur, this is the result, try again whith the branch "trayicons" https://i.imgur.com/Y56CtAq.png

**Comment by btd1337** [comment]
Now it's a little better. 

I think the sound indicator needs a small reduction in its height so that it matches better with the wifi indicator and the battery indicator. And wifi needs more one trace.  (Looks the OSX panel how wifi icon seems bigger than sound icon).

Apparently OSX allows rectangular icons, while Gnome uses 24x24 or 16x16 px (square), this influences the battery indicator appearance.

![captura de tela de 2019-02-22 21-52-36](https://user-images.githubusercontent.com/11943860/53279073-4e93c680-36ec-11e9-9d5e-c09fcd0d5569.png)


![captura de tela de 2019-02-22 21-52-52](https://user-images.githubusercontent.com/11943860/53279078-55223e00-36ec-11e9-9c45-40af08bfcd34.png)

**Comment by btd1337** [comment]
Problem on the brightness indicator icon

![captura de tela de 2019-02-26 13-28-49](https://user-images.githubusercontent.com/11943860/53429033-9bb4b880-39ca-11e9-9bb6-fc65068fa1a7.png)

**Comment by zayronxio** [comment]
the last commit in theory should improve everything related to the panel icons, at least the most used (wifi, battery, notifications, audio) please try and let me know
