### ISSUE TITLE
Request: Update Eclipse IDE icon

### ISSUE THREAD

**Issue by btd1337** [zayronxio/Macos-sierra-CT#8]
Please, Could you update **Eclipse IDE** icon?

This current icon has 15 years old :/

[Updated icon link](https://user-images.githubusercontent.com/11943860/46922575-7017cf80-cfe1-11e8-845a-0cd198fb546c.png)

Thanks in advance.

**Comment by zayronxio** [comment]
in the next update will be changed, greetings
