### ISSUE TITLE
[Request] EmulationStation icon

### ISSUE THREAD

**Issue by btd1337** [zayronxio/Macos-sierra-CT#9]
- [x] **EmulationStation**
- Comment=A graphical and themeable emulator front-end that allows you to access all your favorite games in one place, even without a keyboard
- Icon=emulationstation
- [Icon Link](https://raw.githubusercontent.com/RetroPie/EmulationStation/master/es-app/src/es_icon.ico)

**Comment by zayronxio** [comment]
icon added
